config/routes.rb
Rails.application.routes.draw do
  get 'todolists/new'
  root to: "homes#top"
  post 'todolists' => 'todolists#create'
  get 'todolists' => 'todolists#index'
  get 'todolists/:id' => 'todolists#show', as: 'todolist'
  get 'todolists/:id/edit' => 'todolists#edit', as: 'edit_todolist'
  patch 'todolists/:id' => 'todolists#update', as: 'update_todolist'
  delete 'todolists/:id' => 'todolists#destroy', as: 'destroy_todolist'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  has_many :tags, dependent: :destroy
  has_one_attached :image
end

app/models/tag.rb
class Tag < ApplicationRecord
	belongs_to :list
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/todolists_controller.rb
class TodolistsController < ApplicationController
  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.score = Language.get_data(list_params[:body])#createアクション内に記述することで、投稿した本文を Language.get_data(list_params[:body]) でAPI側に渡しています。
    tags = Vision.get_image_data(list_params[:image])#createアクション内に記述することで、投稿した画像を Vision.get_image_data(list_params[:image]) でAPI側に渡しています。
    if @list.save
      tags.each do |tag|#API側から返ってきた値をもとに、タグを作成しています
        @list.tags.create(name: tag)
      end
      redirect_to todolist_path(@list.id)
    else
      render :new
    end
  end

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    list = List.find(params[:id])
    list.update(list_params)
    redirect_to todolist_path(list.id)
  end

  def destroy
    list = List.find(params[:id])
    list.destroy
    redirect_to todolists_path
  end

  private

  def list_params
    params.require(:list).permit(:title, :body, :image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/homes/top.html.erb
<div class="text-center">
  <h1>ここはTopページです</h1>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <div class="wrapper">
    <div class="button">
      <a href=""><!--好きな遷移先を記述-->
        <div class="icon">
          <i class="fab fa-facebook-f"></i>
        </div>
          <span>Facebook</span>
      </a>
    </div>
    <div class="button">
      <a href="">
        <div class="icon">
          <i class="fab fa-twitter"></i>
        </div>
          <span>Twitter</span>
      </a>
    </div>
    <div class="button">
      <a href="">
        <div class="icon">
          <i class="fab fa-instagram"></i>
        </div>
          <span>Instagram</span>
      </a>
    </div>
    <div class="button">
      <a href="">
        <div class="icon">
          <i class="fab fa-tiktok"></i>
        </div>
          <span>TikTok</span>
      </a>
    </div>
    <div class="button">
      <a href="">
        <div class="icon">
          <i class="fab fa-youtube"></i>
        </div>
          <span>Youtube</span>
      </a>
    </div>
    <div class="button">
      <a href="">
        <div class="icon">
          <i class="fab fa-line"></i>
        </div>
          <span>LINE</span>
      </a>
    </div>
    <div class="button">
      <a href="">
        <div class="icon">
          <i class="fab fa-github"></i>
        </div>
          <span>Github</span>
      </a>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <h1 class="headline"> All Lists </h1>
  <nav>
    <ul class="nav-list">
      <li class="nav-list-item">
        <%= link_to "Top", root_path %>
      </li>
      <li class="nav-list-item">
        <%= link_to "TodoLists", todolists_path %>
      </li>
      <li class="nav-list-item">
        <%= link_to "New List", todolists_new_path %>
      </li>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleAppDemoApi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Kaushan+Script" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/css/lightbox.css" rel="stylesheet">
    <script src="https://kit.fontawesome.com/cdce8a28a2.js" crossorigin="anonymous"></script>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <main>
    <%= yield %>
    <%= video_tag asset_path("fantasy.mp4"), controls: false, autoplay: true, muted: true, loop: true %>
    </main>
    <%= render 'layouts/footer' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/js/lightbox.min.js" type="text/javascript"></script>
  </body>
</html>

app/views/todolists/edit.html.erb
<div class="text-center">
  <h1>編集画面</h1>
  <%= form_with model:@list, url:"/todolists/#{@list.id}", local:true do |f| %>
    <h4>タイトル</h4>
    <%= f.text_field :title, autofocus: true, class: 'form-control' %>
    <h4>本文</h4>
    <%= f.text_area :body, rows: '4', class: 'form-control' %>
    <h4>画像</h4>
    <h6>現在表示されている画像</h6>
    <p><%= image_tag @list.image.variant(resize: '250x250') %></p>
    <%= f.file_field :image %>
    <%= f.submit '保存' %>
  <% end %>
</div><%= f.text_area :body

app/views/todolists/index.html.erb
<div class="list-wrap">
  <% @lists.each do |list| %>
    <div class="list-box">
      <%= link_to todolist_path(list.id) do %><!--do~end内をリンクにしてる-->
        <div class="image-box">
          <% if list.image.attached? %>
              <%= image_tag list.image.variant(resize: '200x200') %>
          <% end %>
        </div>
      <div class="list-comment">
          <span class="list-title"><%= list.title %></span>
          <span class="list-body"><%= list.body %></span>
          <% if list.score < -0.7 %>
            <p class="sentiment-score"><small>※削除推奨</small></p>
          <% end %>
      </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/todolists/new.html.erb
<div class="text-center">
  <h1>新規投稿</h1>
  <%= form_with model:@list, url:'/todolists', local:true do |f| %>
    <h4>タイトル</h4>
    <%= f.text_field :title, autofocus: true, class: 'form-control' %>
    <h4>本文</h4>
    <%= f.text_area :body, rows: '4', class: 'form-control' %>
    <h4>画像</h4>
    <%= f.file_field :image %>
    <%= f.submit '投稿' %>
  <% end %>
</div>

app/views/todolists/show.html.erb
<div class="text-center">
  <h4>タイトル</h4>
  <p class="show-title"><%= @list.title %></p>
  <h4>本文</h4>
  <p class="show-body"><%= @list.body %></p>
  <% if @list.score < -0.7 %>
    <p class="sentiment-score"><small>※削除推奨</small></p>
  <% end %>
  <h4>画像</h4>
  <% if @list.image.attached? %>
    <%= link_to(image_tag(@list.image.variant(resize: '300x300')), @list.image, data: { lightbox: 'group',title: '投稿画像'}) %>
  <% end %>
  <div class="tag-box">
  <% @list.tags.each do |tag| %>
    <span class="label"><%= tag.name %></span>
  <% end %>
  </div>
  <div class="action-link">
    <%= link_to "削除", destroy_todolist_path(@list.id), method: :delete, "data-confirm" => "本当に削除しますか?", class: "link-item" %>
    <%= link_to "編集", edit_todolist_path(@list.id), class: "link-item" %>
  </div>
</div>